name: eggnstone_flutter_ui
description: "Common Flutter widgets"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
